default_install_hook_types: [pre-commit, pre-push]

# Run Ruff and Prettier on every commit; run BasedPyright on push
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

#  - repo: https://github.com/rbubley/mirrors-prettier
#    rev: "14abee445aea04b39069c19b4bd54efff6775819" # v3.7.4
#    hooks:
#      - id: prettier
#        exclude: "\\.py$"

  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.31.4
    hooks:
      - id: basedpyright
        stages: [pre-push]
